<!-- execute:
  warning: false
  message: false -->

```{r, echo = FALSE, message = FALSE}
setwd("/Users/zhoukuang/Documents/JGY_workspace/lectures/DataVisualization202004/DataBook")
#setwd("E:/JGY_workspace/lectures/DataVisualization202004/DataBook")
library(showtext)
showtext_auto(enable = TRUE)
```
# 案例: 航班数据集分析

```{r}
library(magrittr)
library(tidyverse)
library(modelr)
```


```{r}
library(nycflights13)
head(flights)
```


```{r}
library(lubridate)
flightsNew <- flights %>% 
mutate(date = make_date(year, month, day))
```


```{r}
daily <- flightsNew  %>% 
group_by(by = date)  %>% 
summarise(dayNum = n())
head(daily)
```


```{r}
ggplot(daily, aes(by, dayNum)) +
geom_line()
```


```{r}
dailyNew <- daily  %>% 
mutate(week = wday(by,label=TRUE))
```

```{r}
dailyNewTest <- daily  %>% 
mutate(week = wday(by))
```
- 为什么会出现一个箱子？（石学成）
```{r}
class(dailyNewTest$week)
ggplot(dailyNewTest, aes(week, dayNum)) + 
geom_boxplot(aes(group=week))
```

```{r}
class(dailyNew$week)
p1 <- ggplot(dailyNew, aes(week, dayNum)) + geom_boxplot()
p1
```


```{r}
mod = lm(dayNum~week, data = dailyNew)
mod
```


```{r}
grid <- dailyNew %>%
  data_grid(week) %>%
  add_predictions(mod, "numPred")
grid
```
```{r}
p1 + 
geom_point(data = grid, aes(week, numPred),col="red")
```

- 残差图

```{r}
dailyRes <- dailyNew %>%
  add_residuals(mod)

ggplot(dailyRes, aes(by, resid)) +
  geom_ref_line(h=0, col = "red", size = .2)+
  geom_line()
```

找到残差比较大的点

```{r}
dailyRes  %>% 
  arrange(-abs(resid))  

head(dailyRes)
#filter(abs(resid)>200)
```